name: creeperrevealer
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10.8
  - cudatoolkit=11.7
  - pytorch=1.13.0
  - torchvision=0.14.0
  - pip
  - numpy=1.23.4
  - pip:
    - opencv-python==4.6.0.66
    - imutils==0.5.4
    - timm==0.6.12
    - einops==0.6.0
    - dlib
    - open3d